---
- name: Delete software update group and deployment
  microsoft.mecm.software_update_group:
    site_code: "{{ emergency_patch_site_code }}"
    name: "{{ emergency_patch_software_update_group_name }}"
    state: absent

- name: Remove site PS drive
  microsoft.mecm.site_ps_drive:
    site_code: "{{ emergency_patch_site_code }}"
    state: absent
  when: emergency_patch_remove_site_ps_drive | default(true)
